### ISSUE TITLE
VideoOnDemand from vgtrk.com issue

### ISSUE THREAD

**Issue by SlazE888** [3dyd/issues-ys#1]
Every 10 seconds video is freezes for the same 10 seconds on VideosOnDemand(but **on HLS-tracks only**!) from this site:
 [https://player.vgtrk.com/iframe/video/id/440806/start_zoom/true/showZoomBtn/false/sid/russiatv/?acc_video_id=episode_id/440806/video_id/440806/brand_id/43889/](url)

**Comment by 3dyd** [comment]
By design filter can provide data only of a single file. HLS is chunked streams i.e. it consist of multiple files (few seconds long chunks). Solution taken in this case: filter provides only data of HLS playlist. Then downstream splitter processes this playlist and when necessary downloads chunks by its own. Thus this problem is not on the filter side.

I checked that HLS stream with ffmpeg. Either stream is malformed or ffmpeg cannot correctly process it (there are glitches every 10 seconds like you said). So ffmpeg-based splitter (e.g. LAV Splitter) would have problem with it.
